name = "Foo"
uuid = "1ca8da72-8a40-11ef-2d1e-57f47af2c441"
authors = ["Oliver Daisey <oliverjdaisey@gmail.com>"]
version = "0.1.0"

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[targets]
test = ["Oscar"]